In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

# Use the kagglehub client library to attach Kaggle resources like competitions, datasets, and models to your session
# Learn more about kagglehub: https://github.com/Kaggle/kagglehub/blob/main/README.md

import kagglehub
# kagglehub.dataset_download('<owner>/<dataset-slug>')

/kaggle/input/datasets/avishekmajhi/resume-dataset/final_merged_dataset2.csv

In [2]:
df=pd.read_csv(r'/kaggle/input/datasets/avishekmajhi/resume-dataset/final_merged_dataset2.csv')

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8234 entries, 0 to 8233
Data columns (total 2 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Resume    8234 non-null   object
 1   Category  8234 non-null   object
dtypes: object(2)
memory usage: 128.8+ KB

In [4]:
df['Category'].unique()

array(['Python_Developer', 'Java_Developer', 'Front_End_Developer',
       'Network_Administrator', 'Project_manager', 'Security_Analyst',
       'Software_Developer', 'Systems_Administrator', 'Web_Developer',
       'Database_Administrator'], dtype=object)

In [5]:
category = {
    'Python_Developer': 'Python Developer',
    'Front_End_Developer': 'Frontend Developer',
    'Java_Developer': 'Java Developer',
    'Project_manager': 'Project Manager',
    'Network_Administrator': 'Network Administrator',
    'Security_Analyst': 'Security Analyst',
    'Software_Developer': 'Software Developer',
    'Systems_Administrator': 'Systems Administrator',
    'Web_Developer': 'Web Developer',
    'Database_Administrator': 'Database Administrator',
}

In [6]:
df['Category']=df['Category'].map(category)

In [7]:
df['Category'].unique()

array(['Python Developer', 'Java Developer', 'Frontend Developer',
       'Network Administrator', 'Project Manager', 'Security Analyst',
       'Software Developer', 'Systems Administrator', 'Web Developer',
       'Database Administrator'], dtype=object)

In [8]:
df.duplicated().sum()

np.int64(67)

In [9]:
df.drop_duplicates(inplace=True)

In [10]:
df.describe()

                                                   Resume          Category
count                                                8167              8167
unique                                               8167                10
top     Database Administrator (DBA) Database Administ...  Python Developer
freq                                                    1              1278

In [11]:
df['Category'].value_counts()

Category
Python Developer          1278
Java Developer            1206
Web Developer              968
Database Administrator     920
Security Analyst           875
Systems Administrator      769
Project Manager            722
Frontend Developer         523
Network Administrator      469
Software Developer         437
Name: count, dtype: int64

In [12]:
df['Resume'][203]

"Python Developer Python Developer Python Developer - Rockwell Automation Columbus, OH Work Experience Python Developer Rockwell Automation - Cleveland, OH August 2015 to Present Responsibilities:  Participate in requirement gathering and analysis phase of the project in documenting the business requirements by conducting workshops/meetings with various business users  Worked with team of developers on Python applications for RISK management  Developed Python application for Google Analytics aggregation and reporting  Worked on Python Open stack API's, used Python scripts to update content in the database and manipulate files  Generated Python PostGre SQL Forms to record data of online users  Used Python and PostGre SQL creating graphics, XML processing, data exchange and business logic implementation  Used Pandas API to put the data as time series and tabular form for east timestamp data manipulation and retrieval to handle time series data and do data manipulation  Used Pandas library for statistical Analysis using R Studio  Interfacing with supervisors, artists, systems administrators and production to ensure production deadlines are met  Designed and developed the UI of the website using HTML, XHTML, AJAX, CSS and JavaScript, also used Bootstrap as a mechanism to manage and organize the html page layout  Wrote and executed various MYSQL database queries from Python using Python-MySQL connector and MySQL db package  Involved in development of Web Services using SOAP for sending and getting data from the external interface in the XML format  Worked on development of SQL and stored procedures on MYSQL  Responsible for debugging the project monitored on JIRA (Agile)  Performed troubleshooting, fixed and deployed many Python bug fixes of the two main applications that were a main source of data for both customers and internal customer service team Environment: Python 2.7, PyQT, .NET, PyQuery, MVW, HTML5, Shell Scripting, JSON, Rest, Apache Web Server, SQL, UNIX, Windows, PostgreSQL, and Python libraries such as Numpy, SQLAlchemy, etc. Python Developer Clemson Univ - Clemson, SC October 2014 to August 2015 Responsibilities:  Designed views and templates with Python Django's view controller and templating language to create a web interface  Used on Django's API's to access database objects  Developed user interface using HTML, CSS, AJAX and JavaScript  Worked on API's deploying queries, status codes, requests to retrieve data in json format  Worked on data exchange from website using xml, java and web services  Performed Python GUI programming using Tkinter.  Worked on python scripts to parse XML documents and load the data in database  Coordinated with team members to improve quality assurance and mitigate risks  Wrote stored procedures in MySQL Environment: Python 2.7, PyQT, .NET, PyQuery, MVW, HTML5, Shell Scripting, JSON, Rest, Apache Web Server, SQL, UNIX, Windows, PostgreSQL, and python libraries such as Numpy, SQLAlchemy, etc. Jr. Python Developer Dept of Research & Defense Organization (DRDO) - Hyderabad, Andhra Pradesh May 2011 to August 2014 Responsibilities:  Performed design, involved in code reviews and wrote unit tests in python  Worked on tuples, dictionaries, object oriented concepts based inheritance features for making algorithms  Designed and developed data management system using MySQL  Worked on UI using HTML, CSS and JavaScript  Used Git for version control  Monitored and troubleshot web applications  Performed data analysis, manipulation and reporting using pivot tables and advanced functions in MS excel Environment: Python 2.7, PyQT, .NET, PyQuery, MVW, HTML5, Shell Scripting, JSON, Rest, Apache Web Server, SQL, UNIX, Windows, PostgreSQL, and python libraries such as Numpy, SQLAlchemy, etc. Education B.Tech in Computer Science & Engineering St.Martins College - Hyderabad, Andhra Pradesh"

# Cleaning Text

In [13]:
import re

def clean_text(text):
    text = text.lower()
    text = re.sub(r'http\S+|www\S+', ' ', text)
    text = re.sub(r'[\n\t\r]+', ' ', text)
    text = re.sub(r'[^a-zA-Z0-9+#.\- ]', ' ', text)
    text = re.sub(r'\s+', ' ', text).strip()

    return text

In [14]:
df['Resume']=df['Resume'].apply(clean_text)

In [15]:
def remove_header(text):
    text = re.sub(r'^.*?\s-\s', '', text, count=1)
    return text.strip()

In [16]:
df['Resume']=df['Resume'].apply(remove_header)

In [17]:
from sklearn.preprocessing import LabelEncoder

In [18]:
le=LabelEncoder()
df['label']=le.fit_transform(df['Category'])

In [19]:
print(le.classes_)

['Database Administrator' 'Frontend Developer' 'Java Developer'
 'Network Administrator' 'Project Manager' 'Python Developer'
 'Security Analyst' 'Software Developer' 'Systems Administrator'
 'Web Developer']

In [20]:
df

,Resume,Category,label
0,python developer python developer philadelphia...,Python Developer,5
1,denver co april 2019 to august 2019 contract b...,Python Developer,5
2,nokia solutions and networks software automati...,Python Developer,5
3,prudential financial-newark new jersey profici...,Python Developer,5
4,autodesk san rafael ca 7+ years of experience ...,Python Developer,5
...,...,...,...
8229,sldcada navy weapon station york hyattsville m...,Database Administrator,0
8230,if policies have changed keeping records of al...,Database Administrator,0
8231,sprint nextel charlotte nc over 9+ years of te...,Database Administrator,0
8232,tennessee valley authority knoxville tn experi...,Database Administrator,0
8233,washington dc may 2018 to present department o...,Database Administrator,0

# Train Test Split

In [21]:
from sklearn.model_selection import train_test_split

In [22]:
x = df['Resume']
y = df['label']
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=809)

In [23]:
text=[sentence.split() for sentence in x_train]
print(text[0])

['five9', 'san', 'roman', 'ca', 'park', 'city', 'ut', 'around', '8+years', 'of', 'experience', 'as', 'a', 'web', 'application', 'developer', 'and', 'coding', 'with', 'analytical', 'programming', 'using', 'python', 'django', 'flask', 'aws', 'sql.', 'experienced', 'with', 'full', 'software', 'development', 'life-cycle', 'architecting', 'scalable', 'platforms', 'object', 'oriented', 'programming', 'database', 'design.', 'good', 'experience', 'of', 'software', 'development', 'in', 'python', 'libraries', 'used', 'beautiful', 'soup', 'numpy', 'scipy', 'matplotlib', 'pandas', 'data', 'frame', 'network', 'urllib2', 'mysql', 'db', 'for', 'database', 'connectivity', 'and', 'ides', '-', 'sublime', 'text', 'spyder', 'pycharm.', 'experienced', 'with', 'json', 'based', 'restful', 'web', 'services', 'and', 'xml', 'qml', 'based', 'soap', 'web', 'services', 'and', 'also', 'worked', 'on', 'various', 'applications', 'using', 'python', 'integrated', 'ides', 'like', 'sublime', 'text', 'and', 'pycharm.', 'developed', 'consumer-based', 'features', 'and', 'applications', 'using', 'python', 'django', 'and', 'html.', 'using', 'django', 'evolution', 'and', 'manual', 'sql', 'modifications', 'able', 'to', 'modify', 'django', 'models', 'while', 'retaining', 'all', 'data', 'while', 'site', 'was', 'in', 'production', 'mode.', 'having', 'experience', 'in', 'agile', 'methodologies', 'scrum', 'stories', 'and', 'sprints', 'experience', 'in', 'a', 'python', 'based', 'environment', 'along', 'with', 'data', 'analytics', 'data', 'wrangling', 'and', 'excel', 'data', 'extracts.', 'experienced', 'in', 'nosql', 'technologies', 'like', 'mongodb', 'cassandra', 'and', 'relational', 'databases', 'like', 'oracle', 'sqlite', 'postgresql', 'and', 'mysql', 'databases', 'developed', 'cloud', 'formation', 'templates', 'also', 'launched', 'aws', 'elastic', 'beanstalk', 'for', 'deploying', 'monitoring', 'and', 'scaling', 'web', 'applications', 'using', 'different', 'platforms', 'like', 'docker', 'python', 'etc.', 'hands', 'on', 'experience', 'on', 'wamp', 'windows', 'apache', 'mysql', 'and', 'python', 'and', 'lamp', 'db', 'linux', 'apache', 'mysql', 'and', 'python', 'architecture.', 'expertise', 'in', 'aws', 'resources', 'like', 'ec2', 's3', 'ebs', 'vpc', 'elb', 'ami', 'sns', 'rds', 'iam', 'route', '53', 'auto', 'scaling', 'cloud', 'formation', 'cloud', 'watch', 'security', 'groups.', 'working', 'experience', 'with', 'cloud', 'infrastructure', 'of', 'aws', 'amazon', 'web', 'services', 'and', 'computing', 'ami', 'virtual', 'machines', 'on', 'elastic', 'compute', 'cloud', 'ec2', '.', 'have', 'experience', 'with', 'aws', 'lambda', 'which', 'runs', 'the', 'code', 'with', 'response', 'of', 'events.', 'extensively', 'worked', 'with', 'automation', 'tools', 'like', 'jenkins', 'for', 'continuous', 'integration', 'and', 'continuous', 'delivery', 'ci', 'cd', 'and', 'to', 'implement', 'the', 'end-to-end', 'automation.', 'good', 'hands', 'on', 'experience', 'with', 'go', 'lang', 'and', 'its', 'built-in', 'concurrency', 'features', 'such', 'as', 'go-routines', 'channels', 'and', 'select', 'statement.', 'have', 'good', 'experience', 'on', 'working', 'with', 'version', 'controls', 'like', 'git', 'and', 'github', 'experience', 'in', 'using', 'tomcat', 'apache', 'servers', 'and', 'docker', 'containers', 'for', 'deployment.', 'good', 'idea', 'about', 'testing', 'tools', 'like', 'bugzilla', 'and', 'jira', 'worked', 'closely', 'with', 'designer', 'tightly', 'integrating', 'flash', 'into', 'the', 'cms', 'with', 'the', 'use', 'of', 'flashvars', 'stored', 'in', 'the', 'django', 'models.', 'also', 'created', 'xml', 'with', 'django', 'to', 'be', 'used', 'by', 'the', 'flash.', 'hands', 'on', 'experience', 'in', 'data', 'mining', 'and', 'data', 'warehousing', 'using', 'etl', 'tools', 'and', 'proficient', 'in', 'building', 'reports', 'and', 'dashboards', 'in', 'tableau', 'bi', 'tool', '.', 'good', 'written', 'and', 'communication', 'skills.', 'poses', 'capability', 'to', 'interact', 'very', 'closely', 'with', 'wide', 'range', 'of', 'audience', 'such', 'as', 'engineers', 'scientists', 'health', 'professionals', 'scientists', 'professors', 'clients', 'and', 'vendors', 'authorized', 'to', 'work', 'in', 'the', 'us', 'for', 'any', 'employer', 'work', 'experience', 'python', 'developer', 'five9', 'san', 'roman', 'ca', 'march', '2017', 'to', 'present', 'responsibilities', 'worked', 'on', 'the', 'development', 'of', 'internal', 'testing', 'tool', 'framework', 'written', 'in', 'python.', 'successfully', 'migrated', 'the', 'django', 'database', 'from', 'sqlite', 'to', 'mysql', 'to', 'postgresql', 'with', 'complete', 'data', 'integrity.', 'developed', 'entire', 'frontend', 'and', 'backend', 'modules', 'using', 'python', 'on', 'django', 'including', 'tastypieweb', 'framework', 'using', 'git', 'node', 'js', 'underscore', 'js', 'angular', 'js', 'css', 'and', 'javascript.', 'created', 'apis', 'database', 'model', 'and', 'views', 'utilization', 'python', 'in', 'order', 'to', 'build', 'responsive', 'web', 'page', 'application.', 'used', 'github', 'for', 'python', 'source', 'code', 'version', 'control', 'jenkins', 'for', 'automating', 'the', 'build', 'docker', 'containers', 'and', 'deploying', 'in', 'mesos', 'involved', 'in', 'the', 'complete', 'software', 'development', 'lifecycle', 'sdlc', 'to', 'develop', 'the', 'application.', 'added', 'several', 'options', 'to', 'the', 'application', 'to', 'choose', 'algorithm', 'for', 'data', 'and', 'address', 'generation.', 'used', 'automation', 'jenkins', 'for', 'continuous', 'integration', 'and', 'continuous', 'delivery', 'ci', 'cd', 'on', 'amazon', 'ec2.', 'hands', 'on', 'experience', 'in', 'aws', 'cloud', 'in', 'various', 'aws', 'services', 'such', 'as', 'route', '53', 'domain', 'configuration.', 'designed', 'and', 'developed', 'the', 'framework', 'to', 'consume', 'the', 'web', 'services', 'hosted', 'in', 'amazon', 'ec2.', 'created', 'monitors', 'alarms', 'and', 'notifications', 'for', 'ec2', 'hosts', 'using', 'cloud', 'watch.', 'automated', 'the', 'existing', 'scripts', 'for', 'performance', 'calculations', 'using', 'numpy', 'scipy', 'and', 'sql', 'alchemy.', 'hands', 'on', 'experience', 'with', 'gui', 'tool', 'kit', 'like', 'pyqt.', 'critiqued', 'the', 'source', 'data', 'coming', 'from', 'different', 'sources', 'oracle', 'db2', 'xml', 'flat', 'files', 'and', 'worked', 'on', 'developing', 'etl', 'mappingss', 'the', 'unit', 'test', 'was', 'improved', 'and', 'the', 'existing', 'ones', 'were', 'also', 'fixed.', 'performed', 'code', 'reviews', 'and', 'implemented', 'best', 'pythonic', 'programming', 'practices.', 'good', 'analytical', 'and', 'problem-solving', 'skills', 'and', 'ability', 'to', 'work', 'on', 'own', 'besides', 'being', 'a', 'valuable', 'and', 'contributing', 'team', 'player.', 'environment', 'python', 'html5', 'css3', 'angular.js', 'javascript', 'mysql', 'django', 'django', 'tastypie', 'unix', 'windows', 'postgresql', 'sql', 'alchemy', 'sql', 'aws', 'apache', 'web', 'server', 'git.', 'python', 'developer', 'western', 'digital', 'corporation', '-', 'san', 'jose', 'ca', 'may', '2015', 'to', 'february', '2017', 'responsibilities', 'designed', 'front', 'end', 'and', 'backend', 'of', 'the', 'application', 'using', 'python', 'on', 'django', 'web', 'framework.', 'used', 'html', 'css', 'ajax', 'and', 'json', 'to', 'design', 'and', 'develop', 'the', 'user', 'interface', 'of', 'the', 'website.', 'developed', 'views', 'and', 'templates', 'with', 'python', 'and', 'django', 's', 'view', 'controller', 'and', 'templating', 'language', 'to', 'create', 'a', 'user-friendly', 'website', 'interface.', 'used', 'javascript', 'and', 'json', 'to', 'update', 'a', 'portion', 'of', 'a', 'webpage.', 'hands', 'on', 'experience', 'working', 'with', 'pandas', 'and', 'python', 'libraries.', 'develop', 'consumer-based', 'features', 'and', 'applications', 'using', 'python', 'django', 'html', 'and', 'test-driven', 'development', 'tdd', '.', 'designed', 'and', 'developed', 'a', 'horizontally', 'scalable', 'apis', 'using', 'python', 'flask.', 'rewrite', 'existing', 'python', 'django', 'modules', 'to', 'deliver', 'certain', 'format', 'of', 'data.', 'used', 'jira', 'for', 'bug', 'tracking', 'and', 'issue', 'tracking.', 'worked', 'as', 'part', 'of', 'an', 'agile', 'scrum', 'based', 'development', 'team', 'and', 'exposed', 'to', 'tdd', 'approach', 'in', 'developing', 'applications.', 'worked', 'on', 'deployment', 'of', 'project', 'on', 'to', 'amazon', 's3.', 'used', 'git', 'version', 'control', 'and', 'deployed', 'project.', 'involved', 'in', 'development', 'of', 'web', 'services', 'using', 'soap', 'for', 'sending', 'and', 'getting', 'data', 'from', 'the', 'external', 'interface', 'in', 'the', 'xml', 'qml', 'format.', 'developed', 'api', 'modularizing', 'existing', 'python', 'module', 'with', 'the', 'help', 'of', 'pyyaml', 'libraries.', 'written', 'python', 'modules', 'to', 'extract', 'load', 'asset', 'data', 'from', 'the', 'mysql', 'source', 'database.', 'designed', 'and', 'implemented', 'a', 'dedicated', 'mysql', 'database', 'server', 'to', 'drive', 'the', 'web', 'apps', 'and', 'report', 'on', 'daily', 'progress.', 'developing', 'scalable', 'front-end', 'user', 'interfaces', 'using', 'html', 'css', 'and', 'javascript', 'jquery', 'angular.js', 'and', 'mongo', 'db.', 'build', 'sql', 'queries', 'for', 'performing', 'various', 'crud', 'operations', 'like', 'create', 'update', 'read', 'and', 'delete.', 'hands', 'on', 'experience', 'on', 'working', 'with', 'selenium', 'api.', 'used', 'ansible', 'playbooks', 'to', 'setup', 'continuous', 'integration', 'and', 'continuous', 'delivery', 'ci', 'cd', 'pipeline.', 'this', 'primarily', 'consists', 'of', 'a', 'jenkins', 'and', 'sonar', 'server', 'the', 'infrastructure', 'to', 'run', 'these', 'packages', 'and', 'various', 'supporting', 'software', 'components', 'such', 'as', 'maven', 'etc.', 'exposure', 'on', 'multi-threading', 'factory', 'to', 'distribute', 'learning', 'process', 'back-testing', 'and', 'into', 'various', 'worker', 'processes.', 'worked', 'extensively', 'with', 'bootstrap', 'javascript', 'and', 'jquery', 'to', 'optimize', 'the', 'user', 'experience.', 'skilled', 'in', 'using', 'collections', 'in', 'python', 'for', 'manipulating', 'and', 'looping', 'through', 'different', 'user', 'defined', 'objects.', 'worked', 'in', 'development', 'of', 'applications', 'especially', 'in', 'unix', 'environment', 'and', 'familiar', 'with', 'all', 'of', 'its', 'commands.', 'environment', 'python', '3.6', '2.7', 'django', '2.0', '1.6', 'html5', 'css', 'xml', 'pandas', 'javascript', 'angular', 'js', 'backbone', 'js', 'jquery', 'css', 'bootstrap', 'mongo', 'db', 'ms', 'sql', 'server', 't-sql', 'eclipse', 'git', 'github', 'aws', 'linux', 'shell', 'scripting.fg', 'python', 'developer', 'cargill', 'ks', 'december', '2013', 'to', 'april', '2015', 'responsibilities', 'developed', 'entire', 'frontend', 'and', 'backend', 'modules', 'using', 'python', 'on', 'django', 'web', 'framework.', 'designed', 'and', 'developed', 'rest', 'webservices', 'to', 'interact', 'with', 'various', 'business', 'sectors', 'and', 'used', 'soap', 'protocol', 'for', 'webservices', 'communication.', 'worked', 'on', 'designing', 'coding', 'and', 'developing', 'the', 'application', 'in', 'python', 'using', 'django', 'mvc.', 'consumed', 'restful', 'webservices', 'where', 'the', 'transmission', 'of', 'data', 'is', 'in', 'json', 'format.', 'worked', 'on', 'integrating', 'python', 'with', 'web', 'development', 'tools', 'and', 'web', 'services.', 'wrote', 'and', 'executed', 'various', 'mysql', 'database', 'queries', 'from', 'python', 'using', 'python', 'mysql', 'connector', 'and', 'mysql', 'db', 'package.', 'wrote', 'scripts', 'in', 'python', 'for', 'extracting', 'data', 'from', 'html', 'file.', 'agi', 'designed', 'developed', 'and', 'tested', 'the', 'store', 'management', 'application', 'using', 'html', 'javascript', 'php', 'and', 'postgresql.', 'web', 'development', 'including', 'standardizing', 'the', 'toolsets', 'used', 'from', 'eclipse', 'to', 'use', 'git', 'for', 'source', 'control.', 'utilized', 'pyunit', 'the', 'python', 'unit', 'test', 'framework', 'for', 'all', 'python', 'applications.', 'developed', 'data', 'analytic', 'tools', 'using', 'python', 'pandas', 'and', 'visualizations', 'using', 'matplotlib', 'and', 'bokeh.', 'worked', 'on', 'crud', 'permissions', 'using', 'mysql', 'and', 'presented', 'them', 'with', 'the', 'beautiful', 'wxpython', 'widgets.', 'created', 'new', 'pl', 'sql', 'stored', 'procedures', 'for', 'new', 'oracle', 'forms', 'and', 'reports', 'development.', 'worked', 'on', 'various', 'integrated', 'development', 'environments', 'like', 'pycharm', 'anaconda', 'spyder.', 'automated', 'the', 'existing', 'scripts', 'for', 'performance', 'calculations', 'using', 'numpy', 'scipy', 'and', 'sql', 'alchemy.', 'created', 'restful', 'micro', 'services', 'utilizing', 'flask', 'and', 'django', 'and', 'sent', 'on', 'aws', 'servers', 'utilizing', 'ebs', 'and', 'ec2.', 'performed', 'troubleshooting', 'fixed', 'and', 'deployed', 'many', 'python', 'bug', 'fixes', 'of', 'the', 'two', 'main', 'applications', 'that', 'were', 'a', 'main', 'source', 'of', 'data', 'for', 'both', 'customers', 'and', 'internal', 'customer', 'service', 'team.', 'rewrote', 'existing', 'python', 'django', 'modules', 'to', 'deliver', 'certain', 'format', 'of', 'data.', 'wrote', 'python', 'scripts', 'to', 'parse', 'xml', 'qml', 'documents', 'and', 'load', 'the', 'data', 'in', 'database.', 'experienced', 'in', 'working', 'with', 'various', 'python', 'ide', 's', 'using', 'pycharm', 'pyscripter', 'spyder', 'pystudio', 'pydev', 'sublime', 'text.', 'developed', 'web', 'based', 'dynamic', 'form', 'builder', 'using', 'html', 'css', 'and', 'javascript', 'object-to-xml.', 'used', 'python', 'and', 'django', 'to', 'interface', 'with', 'the', 'jquery', 'ui', 'and', 'manage', 'the', 'storage', 'and', 'deletion', 'of', 'content.', 'used', 'spark', 'for', 'interactive', 'queries', 'processing', 'of', 'streaming', 'data', 'and', 'integration', 'with', 'popular', 'nosql', 'database', 'for', 'huge', 'volume', 'of', 'data', 'involved', 'in', 'converting', 'hive', 'sql', 'queries', 'into', 'spark', 'transformations', 'using', 'spark', 'rdd', 'and', 'python', 'worked', 'on', 'the', 'mysql', 'migration', 'project', 'to', 'make', 'the', 'system', 'completely', 'independent', 'of', 'the', 'database', 'being', 'used.', 'migration', 'of', 'data', 'validation', 'code', 'from', 'the', 'legacy', 'mainframe', 'systems', 'to', 'etl', 'framework', 'using', 'informatica', 'workflows', 'and', 'shell', 'scripts.', 'developed', 'stored', 'procedures', 'functions', 'and', 'packages', 'for', 'etl', 'development.', 'performed', 'the', 'performance', 'evaluation', 'of', 'the', 'etl', 'for', 'full', 'load', 'cycle.', 'critiqued', 'the', 'source', 'data', 'coming', 'from', 'different', 'sources', 'oracle', 'db2', 'xml', 'flat', 'files', 'and', 'worked', 'on', 'developing', 'etl', 'mappings', 'used', 'testing', 'like', 'jira', 'for', 'bug', 'tracking.', 'created', 'oracle', 'database', 'tables', 'stored', 'procedures', 'sequences', 'triggers', 'views.', 'implemented', 'rest', 'apis', 'using', 'python', 'and', 'django', 'framework.', 'created', 'a', 'rich', 'single', 'page', 'application', 'using', 'html', 'css', 'jsp', 'json', 'angular', 'node.js', 'bootstrap.js', 'backbone.js.', 'developed', 'web-based', 'applications', 'using', 'python', 'django', 'xml', 'css', 'html', 'javascript', 'angularjs', 'and', 'jquery.', 'use', 'of', 'agile', 'rally', 'for', 'project', 'management', 'like', 'project', 'iteration', 'etc.', 'used', 'agile', 'rally', 'for', 'scheduling', 'release', 'and', 'other', 'qa', 'activites.', 'worked', 'on', 'wamp', 'windows', 'mysql', 'python', 'php', 'and', 'lamp', 'linux', 'mysql', 'python', 'php', 'architecture.', 'developed', 'views', 'and', 'templates', 'with', 'python', 'and', 'django', 's', 'view', 'controller', 'and', 'templating', 'language', 'to', 'created', 'user-friendly', 'website', 'interface.', 'created', 'data', 'tables', 'utilizing', 'pyqt', 'to', 'display', 'customer', 'and', 'policy', 'information', 'and', 'add', 'delete', 'update', 'customer', 'records.', 'created', 'and', 'deployed', 'web', 'pages', 'using', 'html', 'jsp', 'javascript', 'and', 'css.', 'environment', 'python', 'django', 'html', 'css', 'xml', 'qml', 'javascript', 'go', 'lang', 'ajax', 'webserver', 'wxpython', 'matplotlib', 'numpy', 'pydev', 'postgresql', 'apache', 'bootstrap', 'flask', 'oracle', 'pl', 'sql', 'mysql', 'ms-sql', 'web', 'services', 'soap', 'rest', 'pycharm', 'windows', 'linux.', 'python', 'application', 'developer', 'interactions', 'ma', 'june', '2011', 'to', 'november', '2013', 'responsibilities', 'maintained', 'program', 'libraries', 'users', 'manuals', 'and', 'technical', 'documentation.', 'managed', 'large', 'datasets', 'using', 'panda', 'data', 'frames', 'and', 'mysql.', 'wrote', 'and', 'executed', 'various', 'mysql', 'database', 'queries', 'from', 'python', 'using', 'python-mysql', 'connector', 'and', 'mysql', 'db', 'package.', 'thorough', 'knowledge', 'in', 'various', 'front', 'end', 'tools', 'like', 'html', 'css', 'javascript', 'xml', 'jquery', 'angular', 'js', 'and', 'ajax.', 'managed', 'large', 'datasets', 'using', 'panda', 'data', 'frames', 'and', 'mysql.', 'hands-on', 'experience', 'in', 'writing', 'and', 'reviewing', 'requirements', 'architecture', 'documents', 'test', 'plans', 'design', 'documents', 'quality', 'analysis', 'and', 'audits.', 'built', 'various', 'graphs', 'for', 'business', 'decision-making', 'using', 'python', 'matplotlib', 'library.', 'fetched', 'twitter', 'feeds', 'for', 'certain', 'important', 'keyword', 'using', 'python-twitter', 'library.', 'used', 'python', 'library', 'beautiful', 'soup', 'for', 'webscrapping.', 'formulating', 'the', 'etl', 'mappings', 'to', 'implement', 'the', 'business', 'logic.', 'used', 'transformations', 'like', 'lookup', 'update', 'strategy', 'expression', 'filter', 'router', 'aggregate', 'source', 'qualifier.', 'exposure', 'about', 'etl', 'batch', 'and', 'the', 'concept', 'of', 'data', 'warehousing.', 'have', 'extensively', 'worked', 'on', 'creating', 'different', 'kinds', 'of', 'maps', 'graphs', 'etc', 'for', 'analysis', 'of', 'data', 'in', 'tableau.', 'have', 'experience', 'working', 'on', 'creating', 'calculated', 'fields', 'by', 'joining', 'different', 'kinds', 'of', 'data', 'sets', 'from', 'different', 'data', 'sources', 'in', 'tableau.', 'designed', 'tableau', 'dashboards', 'templates', 'for', 'market', 'reports', 'by', 'tableau', 'dashboards', 'and', 'pivot', 'tables.', 'created', 'reports', 'in', 'tableau', 'for', 'visualization', 'of', 'the', 'data', 'sets', 'created', 'and', 'tested', 'impala', 'connectors.', 'worked', 'on', 'hdfs', 'to', 'store', 'and', 'access', 'huge', 'datasets', 'within', 'hadoop', 'developed', 'different', 'kind', 'of', 'custom', 'filters', 'and', 'handled', 'pre-defined', 'filters', 'on', 'hbase', 'data', 'using', 'api.', 'developed', 'user', 'interface', 'solutions', 'using', 'a', 'django', 'web', 'framework.', 'used', 'python', 'scripts', 'to', 'update', 'content', 'in', 'the', 'database', 'and', 'manipulate', 'files.', 'involved', 'in', 'building', 'database', 'model', 'apis', 'and', 'views', 'utilizing', 'python', 'technologies', 'to', 'build', 'web', 'based', 'applications.', 'developed', 'interfaces', 'using', 'javascript', 'html', 'technologies', 'for', 'several', 'web', 'applications', 'to', 'fetch', 'and', 'graphically', 'present', 'required', 'data', 'from', 'database.', 'involved', 'in', 'the', 'complete', 'software', 'development', 'life', 'cycle', 'sdlc', 'to', 'develop', 'application.', 'developed', 'user', 'interface', 'of', 'the', 'web', 'application', 'using', 'html', 'css3', 'and', 'bootstrap.', 'wrote', 'custom', 'user', 'defined', 'functions', 'in', 'javascript', 'to', 'validate', 'application', 'functionalities', 'features.', 'responsible', 'for', 'writing', 'oop', 'code', 'in', 'python', 'for', 'server', 'side', 'scripting.', 'wrote', 'cod

In [24]:
from gensim.models import Word2Vec

w2v=Word2Vec(min_count=2, window=10, epochs=20, workers=4, vector_size=100)

In [25]:
w2v.build_vocab(text)
print(w2v.wv)

KeyedVectors<vector_size=100, 46602 keys>

In [26]:
w2v.train(text, total_examples=w2v.corpus_count, epochs=10)

(56134152, 68220290)

In [28]:
w2v.wv.similarity('python', 'machine')

np.float32(0.19460803)

# Tokenization

In [29]:
from tensorflow.keras.preprocessing.text import Tokenizer

In [32]:
tk=Tokenizer(num_words=1000, oov_token="<OOV>")
tk.fit_on_texts(x_train)

In [33]:
x_train_seq=tk.texts_to_sequences(x_train)
x_test_seq=tk.texts_to_sequences(x_test)

In [34]:
from tensorflow.keras.preprocessing.sequence import pad_sequences

max_len=500
x_train_pad=pad_sequences(x_train_seq, maxlen=max_len, padding='pre', truncating='post')
x_test_pad=pad_sequences(x_test_seq, maxlen=max_len, padding='pre', truncating='post')

In [37]:
x_train_pad[10]

array([  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
         0,   0,   0,   0,   0,   0,   0, 862,  75, 235, 862,  75, 235,
         1,   2,   1, 105,   1, 317,   1,   1,   1,  10, 452,   7, 440,
       939, 656,   1, 168,   1,   1,   3, 348,   1,  33, 440,  71,   5,
         4,   1, 440, 656,   1,  91, 117,  67, 216,   1,   7, 656,   1,
       240,   1, 146,   1,   7,  70,  80,   1, 348,   7, 177,   5,   4,
       974,   7, 133,  24,   1,   1,   1,   1,   1,   1,   1,   1,   1,
         2, 240,   1,   3,   4, 656, 190,   1,   1,  13,   1,   1,   1,
       105,   1,  80, 754,   1,   3,   1,   1,   5, 453,   3, 697,   4,
       656,   1, 818,   2,   1, 190,   4,   1, 179,   1,   3,   1, 440,
       422,   3, 484,   4, 193,   1, 211,   3,   1,   2, 614, 247, 651,
         3,  69,   5,   4, 447,   6, 289, 686,  69,  19, 862,  75, 235,
       447,   1, 242, 124,   3, 132,   1,   1,  10, 809, 236,   2, 585,
         1,   4, 292,  91, 846,   1,   1,  80, 174,  65,   3,   4, 858,
         2, 240,   1, 950,   1,   3,   1,   5,   4,   1,   1, 159, 228,
       736, 138,   1,  70,  89,  54, 303, 416, 133,  71,   1,  71,   1,
       875, 911,   1,   1,   1,   1], dtype=int32)

# Creating Embedding Matrix

In [39]:
embedding_dim=100
vocab_size=20000

embedding_matrix=np.zeros((vocab_size, embedding_dim))
word_index=tk.word_index

for word, index in word_index.items():
    if index>=vocab_size:
        continue
    if word in w2v.wv:
        embedding_matrix[index]=(w2v.wv[word])

In [40]:
embedding_matrix

array([[ 0.        ,  0.        ,  0.        , ...,  0.        ,
         0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.        , ...,  0.        ,
         0.        ,  0.        ],
       [-1.40627158, -0.40240234, -0.34983286, ...,  2.29193711,
        -2.49250507,  0.9510203 ],
       ...,
       [-0.07263914,  0.09748906, -0.11159912, ...,  0.05832127,
        -0.14549121, -0.08865993],
       [-0.00406413,  0.06220247,  0.00795916, ..., -0.14334609,
         0.07757011,  0.07671235],
       [-0.08258462,  0.0467409 , -0.06098237, ..., -0.0409642 ,
         0.00759439,  0.09917218]])

# Model Training

In [50]:
from keras.models import Sequential
from keras.layers import Input, Dense, Embedding, Bidirectional, LSTM, Dropout
from tensorflow.keras.callbacks import EarlyStopping

In [45]:
embedding=Embedding(input_dim=20000, output_dim=100, trainable=True, weights=[embedding_matrix])

In [54]:
model=Sequential()

model.add(Input(shape=(500,)))
model.add(embedding)

model.add(Bidirectional(LSTM(128)))
model.add(Dropout(0.3))

model.add(Dense(32, activation='relu'))
model.add(Dropout(0.3))

model.add(Dense(10, activation='softmax'))
model.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_1 (Embedding)         │ (None, 500, 100)       │     2,000,000 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ bidirectional_1 (Bidirectional) │ (None, 256)            │       234,496 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_2 (Dropout)             │ (None, 256)            │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 32)             │         8,224 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_3 (Dropout)             │ (None, 32)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_3 (Dense)                 │ (None, 10)             │           330 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 2,243,050 (8.56 MB)

 Trainable params: 2,243,050 (8.56 MB)

 Non-trainable params: 0 (0.00 B)

In [55]:
early_stopping=EarlyStopping(monitor='val_loss', patience=3, restore_best_weights=True)

In [56]:
model.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['Accuracy'])

In [57]:
model.fit(x_train_pad, y_train, epochs=100, batch_size=256, validation_split=0.2, callbacks=[early_stopping])

Epoch 1/100
21/21 ━━━━━━━━━━━━━━━━━━━━ 5s 144ms/step - Accuracy: 0.2191 - loss: 2.1490 - val_Accuracy: 0.3527 - val_loss: 1.9147
Epoch 2/100
21/21 ━━━━━━━━━━━━━━━━━━━━ 3s 125ms/step - Accuracy: 0.3435 - loss: 1.8358 - val_Accuracy: 0.4698 - val_loss: 1.6007
Epoch 3/100
21/21 ━━━━━━━━━━━━━━━━━━━━ 3s 125ms/step - Accuracy: 0.4533 - loss: 1.5115 - val_Accuracy: 0.5769 - val_loss: 1.2324
Epoch 4/100
21/21 ━━━━━━━━━━━━━━━━━━━━ 3s 125ms/step - Accuracy: 0.5626 - loss: 1.2252 - val_Accuracy: 0.6611 - val_loss: 0.9970
Epoch 5/100
21/21 ━━━━━━━━━━━━━━━━━━━━ 3s 125ms/step - Accuracy: 0.6391 - loss: 1.0199 - val_Accuracy: 0.7100 - val_loss: 0.8348
Epoch 6/100
21/21 ━━━━━━━━━━━━━━━━━━━━ 3s 125ms/step - Accuracy: 0.6649 - loss: 0.9692 - val_Accuracy: 0.6963 - val_loss: 0.8846
Epoch 7/100
21/21 ━━━━━━━━━━━━━━━━━━━━ 3s 126ms/step - Accuracy: 0.7019 - loss: 0.8586 - val_Accuracy: 0.7184 - val_loss: 0.8154
Epoch 8/100
21/21 ━━━━━━━━━━━━━━━━━━━━ 3s 126ms/step - Accuracy: 0.7262 - loss: 0.7672 - val_Accuracy: 0.7161 - val_loss: 0.8063
Epoch 9/100
21/21 ━━━━━━━━━━━━━━━━━━━━ 3s 125ms/step - Accuracy: 0.7237 - loss: 0.7712 - val_Accuracy: 0.7299 - val_loss: 0.8086
Epoch 10/100
21/21 ━━━━━━━━━━━━━━━━━━━━ 3s 125ms/step - Accuracy: 0.7511 - loss: 0.6946 - val_Accuracy: 0.7467 - val_loss: 0.7481
Epoch 11/100
21/21 ━━━━━━━━━━━━━━━━━━━━ 3s 125ms/step - Accuracy: 0.7694 - loss: 0.6438 - val_Accuracy: 0.7490 - val_loss: 0.7314
Epoch 12/100
21/21 ━━━━━━━━━━━━━━━━━━━━ 3s 125ms/step - Accuracy: 0.7868 - loss: 0.5909 - val_Accuracy: 0.7544 - val_loss: 0.7235
Epoch 13/100
21/21 ━━━━━━━━━━━━━━━━━━━━ 3s 125ms/step - Accuracy: 0.7901 - loss: 0.5698 - val_Accuracy: 0.7666 - val_loss: 0.6573
Epoch 14/100
21/21 ━━━━━━━━━━━━━━━━━━━━ 3s 125ms/step - Accuracy: 0.7847 - loss: 0.6089 - val_Accuracy: 0.7376 - val_loss: 0.7553
Epoch 15/100
21/21 ━━━━━━━━━━━━━━━━━━━━ 3s 125ms/step - Accuracy: 0.7945 - loss: 0.5648 - val_Accuracy: 0.7521 - val_loss: 0.7443
Epoch 16/100
21/21 ━━━━━━━━━━━━━━━━━━━━ 3s 125ms/step - Accuracy: 0.8048 - loss: 0.5300 - val_Accuracy: 0.7605 - val_loss: 0.6932

In [83]:
def predict(resume):
    cleaned = clean_text(resume)
    cleaned = remove_header(cleaned)

    sequence = tk.texts_to_sequences([cleaned])

    padded = pad_sequences(sequence,maxlen=500,padding='pre',truncating='post')

    probabilities = model.predict(padded, verbose=0)[0]
    top_5_indices = np.argsort(probabilities)[::-1][:5]

    results = []

    print("Top 5 Recommended Roles:\n")

    for rank, index in enumerate(top_5_indices, start=1):

        role = le.inverse_transform([index])[0]
        probability = probabilities[index]

        print(f"{rank}. {role}: {probability * 100:.2f}%")

        results.append({"role": role,"probability": probability})

In [84]:
resume="""
Innovative Data Scientist and Python Developer with 5+ years of experience specializing in Natural Language Processing (NLP), Machine Learning (ML), and Large Language Models (LLMs). Expert at transforming unstructured text data into actionable business insights and deploying scalable Artificial Intelligence (AI) pipelines. Proven track record of improving text classification accuracy by 25% using state-of-the-art transformers.
"""

predict(resume)

Top 5 Recommended Roles:

1. Python Developer: 95.50%
2. Project Manager: 1.24%
3. Database Administrator: 1.00%
4. Java Developer: 0.96%
5. Web Developer: 0.67%